# Generated by Django 4.2 on 2023-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Student',
        ),
    ]
